# Generated by Django 3.1.4 on 2020-12-17 05:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 17, 5, 16, 55, 827106, tzinfo=utc), verbose_name='Дата публикации'),
        ),
    ]
