# Generated by Django 3.1.4 on 2020-12-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Аватарка'),
        ),
    ]
